# Generated by Django 5.1.1 on 2024-09-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='mechanic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
